#====================
# íËêîêÈåæ
#====================

LOG_LEVEL_ERR = 5
LOG_LEVEL_WAR = 4
LOG_LEVEL_INF = 3
LOG_LEVEL_DBG = 2
LOG_LEVEL_OTH = 1

ENV_TOKEN_KEY = "HTTP_X-PWSP-AUTH"
ENV_TOKEN_KEY_IIS = "HTTP_X_PWSP_AUTH"
ENV_TOKEN_KEY_FLASK = "X-Pwsp-Auth"

BLOCKCHAIN_NEIGHBOURS_IP_RANGE_NUM = (0, 1)
BLOCKCHAIN_PORT_RANGE = (5000, 5003)

BLOCKCHAIN_MINING_DIFFICULTY = 3
BLOCKCHAIN_MINING_SENDER = 'THE BLOCKCHAIN'
BLOCKCHAIN_MINING_REWARD = 1.0
BLOCKCHAIN_MINING_TIMER_SEC = 20
BLOCKCHAIN_NEIGHBOURS_SYNC_TIME_SEC = 5

BLOCKCHAIN_TYPE_POINT = 1
BLOCKCHAIN_TYPE_NFT = 2

BLOCKCHAIN_SEMAPHORE_NEIGHBOURS = 1
BLOCKCHAIN_SEMAPHORE_SDK = 2
